'use client'

import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';


const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
  });
  
  const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
  });
  
  const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
  };

  
const inter = Inter({ subsets: ['latin'] });

interface Props {
     children: React.ReactNode; 
} 

export default function NavigationLayout( { children }: Props) {

	
	return (
			<div>
				{children}
			</div>
	);
}