Version: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  labels:
    app: nextjs
spec:
  replicas: 1  # Use 1 for dev, 2–3 for staging, 3+ for prod
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: your-registry/nextjs:latest  # Replace with actual image tag
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: nextjs-config
                  key: NODE_ENV
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: nextjs-config
                  key: API_BASE_URL
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
