apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer  # Use ClusterIP for internal services, LoadBalancer for public access
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
